[package]
name = "blur"
version = "0.2.0"
edition = "2021"
repository = "https://github.com/animafps/blur"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0", features = ["derive"] }
dirs = "4.0.0"
rand = "0.8.5" 
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
human-panic = "1.0.3"
rfd = "0.7.0"
indicatif = "0.17.0-rc.2"
regex = "1.5.4"