[package]
name = "teres"
version = "0.2.2"
edition = "2021"
repository = "https://github.com/animafps/teres"
authors = ["Anima <contact@animafps.xyz>"]
license = "GPL-3.0-or-later"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1", features = ["derive"] }
dirs = "4.0.0"
rand = "0.8.5" 
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
human-panic = "1.0.3"
rfd = "0.8.0"
indicatif = "0.16.2"
regex = "1.5.4"
ctrlc = "3.2.1"

[build-dependencies]
clap_mangen = "0.1"
clap = { version = "3.1", features = ["derive"] }